# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NIRbyCellexport.py
# Created on: 2018-05-25 09:53:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: NIRbyCellexport <p_417> <p30m_417> <pn_417> <kpn_417> <NIR_417> 
# Description: 
# Requires input raster of precipitation detph (feet) in IDTM83 projection.  Precipitation raster is resampled to 30m x 30m.  Mean non-irrigated recharge depth (feet) by model cell is calculated using the equation Recharge =K*Precip^N.  K and N value rasters for thick soil, thin soil, and basalt were created based on the ESPAM2.1 soil map and IWRRI Technical Report 04-006.  
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Script arguments
p_417 = arcpy.GetParameterAsText(0)
if p_417 == '#' or not p_417:
    p_417 = "D:\\ESRP\\RechargeData_Alex\\PRE\\PRISM_Grid\\p_417" # provide a default value if unspecified

p30m_417 = arcpy.GetParameterAsText(1)
if p30m_417 == '#' or not p30m_417:
    p30m_417 = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\PrecipRsmp\\p30m_417" # provide a default value if unspecified

pn_417 = arcpy.GetParameterAsText(2)
if pn_417 == '#' or not pn_417:
    pn_417 = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\PrecipToN\\pn_417" # provide a default value if unspecified

kpn_417 = arcpy.GetParameterAsText(3)
if kpn_417 == '#' or not kpn_417:
    kpn_417 = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\KxPrecipToN\\kpn_417" # provide a default value if unspecified

NIR_417 = arcpy.GetParameterAsText(4)
if NIR_417 == '#' or not NIR_417:
    NIR_417 = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\KPNbyCell\\NIR_417" # provide a default value if unspecified

# Local variables:
soiln = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\soiln"
soilk = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\soilk"
ESPAM2_ModelGrid_06092011_shp = "D:\\ESRP\\RechargeData_Alex\\Base\\ESPAM2_ModelGrid_06092011.shp"

# Process: Resample
arcpy.Resample_management(p_417, p30m_417, "30 30", "NEAREST")

# Process: Power
arcpy.gp.Power_sa(p30m_417, soiln, pn_417)

# Process: Times
arcpy.gp.Times_sa(pn_417, soilk, kpn_417)

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(ESPAM2_ModelGrid_06092011_shp, "CELL_INTGR", kpn_417, NIR_417, "DATA", "MEAN")

