# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NIRscript.py
# Created on: 2018-03-06 10:06:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: NIRscript <nir_343> <Field_Name> <Field_Name__2_> <Expression> 
# Description: Created by Alex Moody for batch creation of NIR files
# ---------------------------------------------------------------------------

# Import arcpy module 
import arcpy
import numpy as np

for sp in range(447,450):
	nir_x = "D:\\ESRP\\RechargeData_Alex\\NIR\\GIS\\KPNbyCell\\nir_{0}".format(sp)
	NIRTable="NIRTable"

	# Process: Add Field
	arcpy.AddField_management(NIRTable, "S{0}".format(sp), "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
	# Process: Add Join
	arcpy.AddJoin_management(NIRTable, "CELL_INTGR", nir_x, "CELL_INTGR", "KEEP_ALL")
	# Process: Calculate Field
	arcpy.CalculateField_management(NIRTable, "NIRTable.S{}".format(sp), "[nir_{0}:MEAN]".format(sp), "VB", "")
	# Process: Remove Join
	arcpy.RemoveJoin_management(NIRTable, "")