# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NIRTable.py
# Created on: 2018-03-06 10:36:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: NIRTable <nir_343> <Field_Name> <Field_Name__2_> <Expression> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
nir_343 = arcpy.GetParameterAsText(0)
if nir_343 == '#' or not nir_343:
    nir_343 = "F:\\ESPAM22\\RechargeData_22\\RechargeData_22\\NIR\\GIS\\KPNbyCell\\nir_343" # provide a default value if unspecified

Field_Name = arcpy.GetParameterAsText(1)
if Field_Name == '#' or not Field_Name:
    Field_Name = "S343" # provide a default value if unspecified

Field_Name__2_ = arcpy.GetParameterAsText(2)
if Field_Name__2_ == '#' or not Field_Name__2_:
    Field_Name__2_ = "NIRTable.S343" # provide a default value if unspecified

Expression = arcpy.GetParameterAsText(3)
if Expression == '#' or not Expression:
    Expression = "[nir_343:MEAN]" # provide a default value if unspecified

# Local variables:
NIRTable = "NIRTable"
NIRTable__3_ = nir_343
NIRTable__4_ = NIRTable__3_
NIRTable__5_ = NIRTable__4_
NIRTable__2_ = Field_Name

# Process: Add Field
arcpy.AddField_management(NIRTable, Field_Name, "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Join
arcpy.AddJoin_management(NIRTable__2_, "CELL_INTGR", nir_343, "CELL_INTGR", "KEEP_ALL")

# Process: Calculate Field
arcpy.CalculateField_management(NIRTable__3_, Field_Name__2_, Expression, "VB", "")

# Process: Remove Join
arcpy.RemoveJoin_management(NIRTable__4_, "")

