DIV:
FPT:
  E1:
    name: Covington Brothers
    SiteID: 13038047
  E2:
    name: USBR Ex 2
    SiteID: 13050570
  E3:
    name: Steveco Canyon
    SiteID: 13054588
  E4:
    name: Canyon Creek Lateral
    SiteID: 13055041
  E5:
    name: V Schwendiman
    SiteID: 13055044
  E6:
    name: D Bott
    SiteID: 13055199
  E7:
    name: USBR Ex 5
    SiteID: 13055304
  E8:
    name: Hoopes Brothers
    SiteID: 13055316
  E9:
    name: R. Brent Ricks
    SiteID: 13054772
  E10:
    name: Ehco Ranch
    SiteID: 13055318
  E11:
    name: D L & R Ard
    SiteID: 13055324
  E12:
    name: Hink Inc
    SiteID: 13055326
  E13:
    name: R & J Brown
    SiteID: 13055329
  E14:
    name: USBR Ex 3
    SiteID: 13055343
  E15:
    name: USBR Ex 1
    SiteID: 13056505
  E16:
    name: L. Loosli Pseud
    SiteID: 13048549
  E17:
    name: C. Hoopes
    SiteID: 13055200
  E18:
    name: B. Parkinson
    SiteID: 13055043
  E19:
    name: M. Parkinson
    SiteID: 13055045